apiVersion: v1
data:
  color.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Color App</title>
        <style>
            body {
                margin: 0;
                padding: 0;
                height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
            }
            .full-screen {
                width: 100%;
                height: 100%;
            }
            .red {
                background-color: red;
            }
            .blue {
                background-color: blue;
            }
            .green {
                background-color: green;
            }
            .yellow {
                background-color: yellow;
            }
            .white {
                background-color: white;
            }
        </style>
    </head>
    <body>
        <form action="/color" method="post">
            <button type="submit" name="color" value="red">Red</button>
            <button type="submit" name="color" value="blue">Blue</button>
            <button type="submit" name="color" value="green">Green</button>
            <button type="submit" name="color" value="yellow">Yellow</button>
            <button type="submit" name="color" value="white">White</button>
        </form>

        <script>
            const form = document.querySelector('form');
            form.addEventListener('submit', (e) => {
                e.preventDefault();
                const color = e.submitter.value;
                document.body.className = `full-screen ${color}`;
            });
        </script>
    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: color-app-config
